development:
  adapter: postgresql
  encoding: unicode
  database: peanut-gallery_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: peanut-gallery_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: peanut-gallery_production
  pool: 5
  username:
  password:
